management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8004
  tomcat:
    threads:
      max: 1000

spring:
  application:
    name: files-service
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:testdata.sql
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 100
      #获取连接时最大等待时间
      max-wait: 60000
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000
  data:
    mongodb:
      uri: mongodb://121.4.32.18:27017
      database: middle_friendlink

mybatis:
  #po对象的包
  type-aliases-package: cn.edu.files.model
  #mapper.xml所在的位置
  mapper-locations: classpath*:cn.edu.files.mapper/*.xml
  #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
  configuration:
    #输出产生的SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#minio:
#  endpoint: http://127.0.0.1:9000 #Minio服务所在地址
#  bucketName: file #存储桶名称
#  accessKey: minioadmin #访问的key
#  secretKey: minioadmin #访问的秘钥

minio:
  endpoint: http://znbwc.cn:8001 #Minio服务所在地址
  bucketName: picture #存储桶名称
  accessKey: admin #访问的key
  secretKey: wang123456789 #访问的秘钥

userservice:
  #是否对数据库中的未初始化的数据初始化
  initialization: false
  #分布式锁失效时间（秒）
  lockerExpireTime: 30
  #图片存储位置
  imglocation: ./img
  user:
    # user的权限字在Redis中失效秒数
    expiretime: 600
  role:
    # role的权限字在Redis中失效秒数
    expiretime: 600
  login:
    #是否允许重复登录
    multiply: false
    #jwt过期的时间(秒)
    jwtExpire: 3600


#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
