package cn.xmu.user.model.po;

public class FansPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.writer_id
     *
     * @mbg.generated
     */
    private String writerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.fan_id
     *
     * @mbg.generated
     */
    private String fanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.face
     *
     * @mbg.generated
     */
    private String face;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.fan_nickname
     *
     * @mbg.generated
     */
    private String fanNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.id
     *
     * @return the value of fans.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.id
     *
     * @param id the value for fans.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.writer_id
     *
     * @return the value of fans.writer_id
     *
     * @mbg.generated
     */
    public String getWriterId() {
        return writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.writer_id
     *
     * @param writerId the value for fans.writer_id
     *
     * @mbg.generated
     */
    public void setWriterId(String writerId) {
        this.writerId = writerId == null ? null : writerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.fan_id
     *
     * @return the value of fans.fan_id
     *
     * @mbg.generated
     */
    public String getFanId() {
        return fanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.fan_id
     *
     * @param fanId the value for fans.fan_id
     *
     * @mbg.generated
     */
    public void setFanId(String fanId) {
        this.fanId = fanId == null ? null : fanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.face
     *
     * @return the value of fans.face
     *
     * @mbg.generated
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.face
     *
     * @param face the value for fans.face
     *
     * @mbg.generated
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.fan_nickname
     *
     * @return the value of fans.fan_nickname
     *
     * @mbg.generated
     */
    public String getFanNickname() {
        return fanNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.fan_nickname
     *
     * @param fanNickname the value for fans.fan_nickname
     *
     * @mbg.generated
     */
    public void setFanNickname(String fanNickname) {
        this.fanNickname = fanNickname == null ? null : fanNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.sex
     *
     * @return the value of fans.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.sex
     *
     * @param sex the value for fans.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.province
     *
     * @return the value of fans.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.province
     *
     * @param province the value for fans.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }
}