management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8002
  tomcat:
    threads:
      max: 1000

spring:
  application:
    name: service-article-html
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000
  data:
    mongodb:
      uri: mongodb://121.4.32.18:27017
      database: middle_friendlink
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/

articlehtmlservice:
  #是否对数据库中的未初始化的数据初始化
  initialization: false
  #分布式锁失效时间（秒）
  lockerExpireTime: 30
  #图片存储位置
  imglocation: ./img
  user:
    # user的权限字在Redis中失效秒数
    expiretime: 600
  role:
    # role的权限字在Redis中失效秒数
    expiretime: 600
  login:
    #是否允许重复登录
    multiply: false
    #jwt过期的时间(秒)
    jwtExpire: 3600


#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql

# 定义freemarker生成的html位置
freemarker:
  html:
    target: E:\COSfiles\Desktop\MW\freemarker_html
    article: E:\COSfiles\Desktop\MW\front-end\imooc-news\portal\a

