package cn.xmu.user.mapper;

import cn.xmu.user.model.po.AppUserPo;
import cn.xmu.user.model.po.AppUserPoExample;
import java.util.List;

public interface AppUserPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated
     */
    long countByExample(AppUserPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated
     */
    int insert(AppUserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated
     */
    int insertSelective(AppUserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated
     */
    List<AppUserPo> selectByExample(AppUserPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated
     */
    AppUserPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppUserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppUserPo record);
}