package cn.xmu.article.model.po;

import java.time.LocalDateTime;

public class ArticlePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_type
     *
     * @mbg.generated
     */
    private Integer articleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_cover
     *
     * @mbg.generated
     */
    private String articleCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.is_appoint
     *
     * @mbg.generated
     */
    private Integer isAppoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_status
     *
     * @mbg.generated
     */
    private Integer articleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.publish_user_id
     *
     * @mbg.generated
     */
    private String publishUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.publish_time
     *
     * @mbg.generated
     */
    private LocalDateTime publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.read_counts
     *
     * @mbg.generated
     */
    private Integer readCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.comment_counts
     *
     * @mbg.generated
     */
    private Integer commentCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.mongo_file_id
     *
     * @mbg.generated
     */
    private String mongoFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.category_id
     *
     * @return the value of article.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.category_id
     *
     * @param categoryId the value for article.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_type
     *
     * @return the value of article.article_type
     *
     * @mbg.generated
     */
    public Integer getArticleType() {
        return articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_type
     *
     * @param articleType the value for article.article_type
     *
     * @mbg.generated
     */
    public void setArticleType(Integer articleType) {
        this.articleType = articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_cover
     *
     * @return the value of article.article_cover
     *
     * @mbg.generated
     */
    public String getArticleCover() {
        return articleCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_cover
     *
     * @param articleCover the value for article.article_cover
     *
     * @mbg.generated
     */
    public void setArticleCover(String articleCover) {
        this.articleCover = articleCover == null ? null : articleCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.is_appoint
     *
     * @return the value of article.is_appoint
     *
     * @mbg.generated
     */
    public Integer getIsAppoint() {
        return isAppoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.is_appoint
     *
     * @param isAppoint the value for article.is_appoint
     *
     * @mbg.generated
     */
    public void setIsAppoint(Integer isAppoint) {
        this.isAppoint = isAppoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_status
     *
     * @return the value of article.article_status
     *
     * @mbg.generated
     */
    public Integer getArticleStatus() {
        return articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_status
     *
     * @param articleStatus the value for article.article_status
     *
     * @mbg.generated
     */
    public void setArticleStatus(Integer articleStatus) {
        this.articleStatus = articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.publish_user_id
     *
     * @return the value of article.publish_user_id
     *
     * @mbg.generated
     */
    public String getPublishUserId() {
        return publishUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.publish_user_id
     *
     * @param publishUserId the value for article.publish_user_id
     *
     * @mbg.generated
     */
    public void setPublishUserId(String publishUserId) {
        this.publishUserId = publishUserId == null ? null : publishUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.publish_time
     *
     * @return the value of article.publish_time
     *
     * @mbg.generated
     */
    public LocalDateTime getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.publish_time
     *
     * @param publishTime the value for article.publish_time
     *
     * @mbg.generated
     */
    public void setPublishTime(LocalDateTime publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.read_counts
     *
     * @return the value of article.read_counts
     *
     * @mbg.generated
     */
    public Integer getReadCounts() {
        return readCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.read_counts
     *
     * @param readCounts the value for article.read_counts
     *
     * @mbg.generated
     */
    public void setReadCounts(Integer readCounts) {
        this.readCounts = readCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.comment_counts
     *
     * @return the value of article.comment_counts
     *
     * @mbg.generated
     */
    public Integer getCommentCounts() {
        return commentCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.comment_counts
     *
     * @param commentCounts the value for article.comment_counts
     *
     * @mbg.generated
     */
    public void setCommentCounts(Integer commentCounts) {
        this.commentCounts = commentCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.mongo_file_id
     *
     * @return the value of article.mongo_file_id
     *
     * @mbg.generated
     */
    public String getMongoFileId() {
        return mongoFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.mongo_file_id
     *
     * @param mongoFileId the value for article.mongo_file_id
     *
     * @mbg.generated
     */
    public void setMongoFileId(String mongoFileId) {
        this.mongoFileId = mongoFileId == null ? null : mongoFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.is_delete
     *
     * @return the value of article.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.is_delete
     *
     * @param isDelete the value for article.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_time
     *
     * @return the value of article.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_time
     *
     * @param createTime the value for article.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.update_time
     *
     * @return the value of article.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.update_time
     *
     * @param updateTime the value for article.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}