package cn.xmu.article.model.po;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class ArticlePoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public ArticlePoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Integer value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Integer value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Integer value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Integer value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Integer> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Integer> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andArticleTypeIsNull() {
            addCriterion("article_type is null");
            return (Criteria) this;
        }

        public Criteria andArticleTypeIsNotNull() {
            addCriterion("article_type is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTypeEqualTo(Integer value) {
            addCriterion("article_type =", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeNotEqualTo(Integer value) {
            addCriterion("article_type <>", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeGreaterThan(Integer value) {
            addCriterion("article_type >", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_type >=", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeLessThan(Integer value) {
            addCriterion("article_type <", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeLessThanOrEqualTo(Integer value) {
            addCriterion("article_type <=", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeIn(List<Integer> values) {
            addCriterion("article_type in", values, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeNotIn(List<Integer> values) {
            addCriterion("article_type not in", values, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeBetween(Integer value1, Integer value2) {
            addCriterion("article_type between", value1, value2, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("article_type not between", value1, value2, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleCoverIsNull() {
            addCriterion("article_cover is null");
            return (Criteria) this;
        }

        public Criteria andArticleCoverIsNotNull() {
            addCriterion("article_cover is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCoverEqualTo(String value) {
            addCriterion("article_cover =", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverNotEqualTo(String value) {
            addCriterion("article_cover <>", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverGreaterThan(String value) {
            addCriterion("article_cover >", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverGreaterThanOrEqualTo(String value) {
            addCriterion("article_cover >=", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverLessThan(String value) {
            addCriterion("article_cover <", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverLessThanOrEqualTo(String value) {
            addCriterion("article_cover <=", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverLike(String value) {
            addCriterion("article_cover like", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverNotLike(String value) {
            addCriterion("article_cover not like", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverIn(List<String> values) {
            addCriterion("article_cover in", values, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverNotIn(List<String> values) {
            addCriterion("article_cover not in", values, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverBetween(String value1, String value2) {
            addCriterion("article_cover between", value1, value2, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverNotBetween(String value1, String value2) {
            addCriterion("article_cover not between", value1, value2, "articleCover");
            return (Criteria) this;
        }

        public Criteria andIsAppointIsNull() {
            addCriterion("is_appoint is null");
            return (Criteria) this;
        }

        public Criteria andIsAppointIsNotNull() {
            addCriterion("is_appoint is not null");
            return (Criteria) this;
        }

        public Criteria andIsAppointEqualTo(Integer value) {
            addCriterion("is_appoint =", value, "isAppoint");
            return (Criteria) this;
        }

        public Criteria andIsAppointNotEqualTo(Integer value) {
            addCriterion("is_appoint <>", value, "isAppoint");
            return (Criteria) this;
        }

        public Criteria andIsAppointGreaterThan(Integer value) {
            addCriterion("is_appoint >", value, "isAppoint");
            return (Criteria) this;
        }

        public Criteria andIsAppointGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_appoint >=", value, "isAppoint");
            return (Criteria) this;
        }

        public Criteria andIsAppointLessThan(Integer value) {
            addCriterion("is_appoint <", value, "isAppoint");
            return (Criteria) this;
        }

        public Criteria andIsAppointLessThanOrEqualTo(Integer value) {
            addCriterion("is_appoint <=", value, "isAppoint");
            return (Criteria) this;
        }

        public Criteria andIsAppointIn(List<Integer> values) {
            addCriterion("is_appoint in", values, "isAppoint");
            return (Criteria) this;
        }

        public Criteria andIsAppointNotIn(List<Integer> values) {
            addCriterion("is_appoint not in", values, "isAppoint");
            return (Criteria) this;
        }

        public Criteria andIsAppointBetween(Integer value1, Integer value2) {
            addCriterion("is_appoint between", value1, value2, "isAppoint");
            return (Criteria) this;
        }

        public Criteria andIsAppointNotBetween(Integer value1, Integer value2) {
            addCriterion("is_appoint not between", value1, value2, "isAppoint");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIsNull() {
            addCriterion("article_status is null");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIsNotNull() {
            addCriterion("article_status is not null");
            return (Criteria) this;
        }

        public Criteria andArticleStatusEqualTo(Integer value) {
            addCriterion("article_status =", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotEqualTo(Integer value) {
            addCriterion("article_status <>", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusGreaterThan(Integer value) {
            addCriterion("article_status >", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_status >=", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusLessThan(Integer value) {
            addCriterion("article_status <", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusLessThanOrEqualTo(Integer value) {
            addCriterion("article_status <=", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIn(List<Integer> values) {
            addCriterion("article_status in", values, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotIn(List<Integer> values) {
            addCriterion("article_status not in", values, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusBetween(Integer value1, Integer value2) {
            addCriterion("article_status between", value1, value2, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("article_status not between", value1, value2, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdIsNull() {
            addCriterion("publish_user_id is null");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdIsNotNull() {
            addCriterion("publish_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdEqualTo(String value) {
            addCriterion("publish_user_id =", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdNotEqualTo(String value) {
            addCriterion("publish_user_id <>", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdGreaterThan(String value) {
            addCriterion("publish_user_id >", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("publish_user_id >=", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdLessThan(String value) {
            addCriterion("publish_user_id <", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdLessThanOrEqualTo(String value) {
            addCriterion("publish_user_id <=", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdLike(String value) {
            addCriterion("publish_user_id like", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdNotLike(String value) {
            addCriterion("publish_user_id not like", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdIn(List<String> values) {
            addCriterion("publish_user_id in", values, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdNotIn(List<String> values) {
            addCriterion("publish_user_id not in", values, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdBetween(String value1, String value2) {
            addCriterion("publish_user_id between", value1, value2, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdNotBetween(String value1, String value2) {
            addCriterion("publish_user_id not between", value1, value2, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNull() {
            addCriterion("publish_time is null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNotNull() {
            addCriterion("publish_time is not null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeEqualTo(LocalDateTime value) {
            addCriterion("publish_time =", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotEqualTo(LocalDateTime value) {
            addCriterion("publish_time <>", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThan(LocalDateTime value) {
            addCriterion("publish_time >", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("publish_time >=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThan(LocalDateTime value) {
            addCriterion("publish_time <", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("publish_time <=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIn(List<LocalDateTime> values) {
            addCriterion("publish_time in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotIn(List<LocalDateTime> values) {
            addCriterion("publish_time not in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("publish_time between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("publish_time not between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andReadCountsIsNull() {
            addCriterion("read_counts is null");
            return (Criteria) this;
        }

        public Criteria andReadCountsIsNotNull() {
            addCriterion("read_counts is not null");
            return (Criteria) this;
        }

        public Criteria andReadCountsEqualTo(Integer value) {
            addCriterion("read_counts =", value, "readCounts");
            return (Criteria) this;
        }

        public Criteria andReadCountsNotEqualTo(Integer value) {
            addCriterion("read_counts <>", value, "readCounts");
            return (Criteria) this;
        }

        public Criteria andReadCountsGreaterThan(Integer value) {
            addCriterion("read_counts >", value, "readCounts");
            return (Criteria) this;
        }

        public Criteria andReadCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("read_counts >=", value, "readCounts");
            return (Criteria) this;
        }

        public Criteria andReadCountsLessThan(Integer value) {
            addCriterion("read_counts <", value, "readCounts");
            return (Criteria) this;
        }

        public Criteria andReadCountsLessThanOrEqualTo(Integer value) {
            addCriterion("read_counts <=", value, "readCounts");
            return (Criteria) this;
        }

        public Criteria andReadCountsIn(List<Integer> values) {
            addCriterion("read_counts in", values, "readCounts");
            return (Criteria) this;
        }

        public Criteria andReadCountsNotIn(List<Integer> values) {
            addCriterion("read_counts not in", values, "readCounts");
            return (Criteria) this;
        }

        public Criteria andReadCountsBetween(Integer value1, Integer value2) {
            addCriterion("read_counts between", value1, value2, "readCounts");
            return (Criteria) this;
        }

        public Criteria andReadCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("read_counts not between", value1, value2, "readCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsIsNull() {
            addCriterion("comment_counts is null");
            return (Criteria) this;
        }

        public Criteria andCommentCountsIsNotNull() {
            addCriterion("comment_counts is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCountsEqualTo(Integer value) {
            addCriterion("comment_counts =", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsNotEqualTo(Integer value) {
            addCriterion("comment_counts <>", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsGreaterThan(Integer value) {
            addCriterion("comment_counts >", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_counts >=", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsLessThan(Integer value) {
            addCriterion("comment_counts <", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsLessThanOrEqualTo(Integer value) {
            addCriterion("comment_counts <=", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsIn(List<Integer> values) {
            addCriterion("comment_counts in", values, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsNotIn(List<Integer> values) {
            addCriterion("comment_counts not in", values, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsBetween(Integer value1, Integer value2) {
            addCriterion("comment_counts between", value1, value2, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_counts not between", value1, value2, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdIsNull() {
            addCriterion("mongo_file_id is null");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdIsNotNull() {
            addCriterion("mongo_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdEqualTo(String value) {
            addCriterion("mongo_file_id =", value, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdNotEqualTo(String value) {
            addCriterion("mongo_file_id <>", value, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdGreaterThan(String value) {
            addCriterion("mongo_file_id >", value, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdGreaterThanOrEqualTo(String value) {
            addCriterion("mongo_file_id >=", value, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdLessThan(String value) {
            addCriterion("mongo_file_id <", value, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdLessThanOrEqualTo(String value) {
            addCriterion("mongo_file_id <=", value, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdLike(String value) {
            addCriterion("mongo_file_id like", value, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdNotLike(String value) {
            addCriterion("mongo_file_id not like", value, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdIn(List<String> values) {
            addCriterion("mongo_file_id in", values, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdNotIn(List<String> values) {
            addCriterion("mongo_file_id not in", values, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdBetween(String value1, String value2) {
            addCriterion("mongo_file_id between", value1, value2, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andMongoFileIdNotBetween(String value1, String value2) {
            addCriterion("mongo_file_id not between", value1, value2, "mongoFileId");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}