package cn.xmu.article.model.po;

import java.time.LocalDateTime;

public class CommentPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.writer_id
     *
     * @mbg.generated
     */
    private String writer_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.father_id
     *
     * @mbg.generated
     */
    private String father_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.article_id
     *
     * @mbg.generated
     */
    private String article_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.article_title
     *
     * @mbg.generated
     */
    private String article_title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.article_cover
     *
     * @mbg.generated
     */
    private String articleCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_user_id
     *
     * @mbg.generated
     */
    private String comment_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_user_nickname
     *
     * @mbg.generated
     */
    private String comment_user_nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_user_face
     *
     * @mbg.generated
     */
    private String comment_user_face;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.writer_id
     *
     * @return the value of comments.writer_id
     *
     * @mbg.generated
     */
    public String getWriterId() {
        return writer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.writer_id
     *
     * @param writer_id the value for comments.writer_id
     *
     * @mbg.generated
     */
    public void setWriterId(String writer_id) {
        this.id=null;
        this.writer_id = writer_id == null ? null : writer_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.father_id
     *
     * @return the value of comments.father_id
     *
     * @mbg.generated
     */
    public String getFatherId() {
        return father_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.father_id
     *
     * @param father_id the value for comments.father_id
     *
     * @mbg.generated
     */
    public void setFatherId(String father_id) {
        this.father_id = father_id == null ? null : father_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.article_id
     *
     * @return the value of comments.article_id
     *
     * @mbg.generated
     */
    public String getArticleId() {
        return article_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.article_id
     *
     * @param article_id the value for comments.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(String article_id) {
        this.article_id = article_id == null ? null : article_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.article_title
     *
     * @return the value of comments.article_title
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return article_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.article_title
     *
     * @param article_title the value for comments.article_title
     *
     * @mbg.generated
     */
    public void setArticleTitle(String article_title) {
        this.article_title = article_title == null ? null : article_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.article_cover
     *
     * @return the value of comments.article_cover
     *
     * @mbg.generated
     */
    public String getArticleCover() {
        return articleCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.article_cover
     *
     * @param articleCover the value for comments.article_cover
     *
     * @mbg.generated
     */
    public void setArticleCover(String articleCover) {
        this.articleCover = articleCover == null ? null : articleCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_user_id
     *
     * @return the value of comments.comment_user_id
     *
     * @mbg.generated
     */
    public String getCommentUserId() {
        return comment_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_user_id
     *
     * @param comment_user_id the value for comments.comment_user_id
     *
     * @mbg.generated
     */
    public void setCommentUserId(String comment_user_id) {
        this.comment_user_id = comment_user_id == null ? null : comment_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_user_nickname
     *
     * @return the value of comments.comment_user_nickname
     *
     * @mbg.generated
     */
    public String getCommentUserNickname() {
        return comment_user_nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_user_nickname
     *
     * @param comment_user_nickname the value for comments.comment_user_nickname
     *
     * @mbg.generated
     */
    public void setCommentUserNickname(String comment_user_nickname) {
        this.comment_user_nickname = comment_user_nickname == null ? null : comment_user_nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_user_face
     *
     * @return the value of comments.comment_user_face
     *
     * @mbg.generated
     */
    public String getCommentUserFace() {
        return comment_user_face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_user_face
     *
     * @param comment_user_face the value for comments.comment_user_face
     *
     * @mbg.generated
     */
    public void setCommentUserFace(String comment_user_face) {
        this.comment_user_face = comment_user_face == null ? null : comment_user_face.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.content
     *
     * @return the value of comments.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.content
     *
     * @param content the value for comments.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.create_time
     *
     * @return the value of comments.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.create_time
     *
     * @param create_time the value for comments.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime create_time) {
        this.create_time = create_time;
    }
}