package cn.xmu.article.model.po;

import java.time.LocalDateTime;

public class CommentPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.writer_id
     *
     * @mbg.generated
     */
    private String writerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.father_id
     *
     * @mbg.generated
     */
    private String fatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.article_id
     *
     * @mbg.generated
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.article_title
     *
     * @mbg.generated
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.article_cover
     *
     * @mbg.generated
     */
    private String articleCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_user_id
     *
     * @mbg.generated
     */
    private String commentUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_user_nickname
     *
     * @mbg.generated
     */
    private String commentUserNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_user_face
     *
     * @mbg.generated
     */
    private String commentUserFace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.writer_id
     *
     * @return the value of comments.writer_id
     *
     * @mbg.generated
     */
    public String getWriterId() {
        return writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.writer_id
     *
     * @param writerId the value for comments.writer_id
     *
     * @mbg.generated
     */
    public void setWriterId(String writerId) {
        this.writerId = writerId == null ? null : writerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.father_id
     *
     * @return the value of comments.father_id
     *
     * @mbg.generated
     */
    public String getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.father_id
     *
     * @param fatherId the value for comments.father_id
     *
     * @mbg.generated
     */
    public void setFatherId(String fatherId) {
        this.fatherId = fatherId == null ? null : fatherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.article_id
     *
     * @return the value of comments.article_id
     *
     * @mbg.generated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.article_id
     *
     * @param articleId the value for comments.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.article_title
     *
     * @return the value of comments.article_title
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.article_title
     *
     * @param articleTitle the value for comments.article_title
     *
     * @mbg.generated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.article_cover
     *
     * @return the value of comments.article_cover
     *
     * @mbg.generated
     */
    public String getArticleCover() {
        return articleCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.article_cover
     *
     * @param articleCover the value for comments.article_cover
     *
     * @mbg.generated
     */
    public void setArticleCover(String articleCover) {
        this.articleCover = articleCover == null ? null : articleCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_user_id
     *
     * @return the value of comments.comment_user_id
     *
     * @mbg.generated
     */
    public String getCommentUserId() {
        return commentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_user_id
     *
     * @param commentUserId the value for comments.comment_user_id
     *
     * @mbg.generated
     */
    public void setCommentUserId(String commentUserId) {
        this.commentUserId = commentUserId == null ? null : commentUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_user_nickname
     *
     * @return the value of comments.comment_user_nickname
     *
     * @mbg.generated
     */
    public String getCommentUserNickname() {
        return commentUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_user_nickname
     *
     * @param commentUserNickname the value for comments.comment_user_nickname
     *
     * @mbg.generated
     */
    public void setCommentUserNickname(String commentUserNickname) {
        this.commentUserNickname = commentUserNickname == null ? null : commentUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_user_face
     *
     * @return the value of comments.comment_user_face
     *
     * @mbg.generated
     */
    public String getCommentUserFace() {
        return commentUserFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_user_face
     *
     * @param commentUserFace the value for comments.comment_user_face
     *
     * @mbg.generated
     */
    public void setCommentUserFace(String commentUserFace) {
        this.commentUserFace = commentUserFace == null ? null : commentUserFace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.content
     *
     * @return the value of comments.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.content
     *
     * @param content the value for comments.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.create_time
     *
     * @return the value of comments.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.create_time
     *
     * @param createTime the value for comments.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }
}