package cn.xmu.files.model.po;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class AppUserPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.face
     *
     * @mbg.generated
     */
    private String face;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.realname
     *
     * @mbg.generated
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.birthday
     *
     * @mbg.generated
     */
    private LocalDate birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.district
     *
     * @mbg.generated
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.active_status
     *
     * @mbg.generated
     */
    private Integer activeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.total_income
     *
     * @mbg.generated
     */
    private Integer totalIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.created_time
     *
     * @mbg.generated
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.updated_time
     *
     * @mbg.generated
     */
    private LocalDateTime updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.id
     *
     * @return the value of app_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.id
     *
     * @param id the value for app_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.mobile
     *
     * @return the value of app_user.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.mobile
     *
     * @param mobile the value for app_user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.nickname
     *
     * @return the value of app_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.nickname
     *
     * @param nickname the value for app_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.face
     *
     * @return the value of app_user.face
     *
     * @mbg.generated
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.face
     *
     * @param face the value for app_user.face
     *
     * @mbg.generated
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.realname
     *
     * @return the value of app_user.realname
     *
     * @mbg.generated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.realname
     *
     * @param realname the value for app_user.realname
     *
     * @mbg.generated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.email
     *
     * @return the value of app_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.email
     *
     * @param email the value for app_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.sex
     *
     * @return the value of app_user.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.sex
     *
     * @param sex the value for app_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.birthday
     *
     * @return the value of app_user.birthday
     *
     * @mbg.generated
     */
    public LocalDate getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.birthday
     *
     * @param birthday the value for app_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.province
     *
     * @return the value of app_user.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.province
     *
     * @param province the value for app_user.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.city
     *
     * @return the value of app_user.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.city
     *
     * @param city the value for app_user.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.district
     *
     * @return the value of app_user.district
     *
     * @mbg.generated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.district
     *
     * @param district the value for app_user.district
     *
     * @mbg.generated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.active_status
     *
     * @return the value of app_user.active_status
     *
     * @mbg.generated
     */
    public Integer getActiveStatus() {
        return activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.active_status
     *
     * @param activeStatus the value for app_user.active_status
     *
     * @mbg.generated
     */
    public void setActiveStatus(Integer activeStatus) {
        this.activeStatus = activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.total_income
     *
     * @return the value of app_user.total_income
     *
     * @mbg.generated
     */
    public Integer getTotalIncome() {
        return totalIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.total_income
     *
     * @param totalIncome the value for app_user.total_income
     *
     * @mbg.generated
     */
    public void setTotalIncome(Integer totalIncome) {
        this.totalIncome = totalIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.created_time
     *
     * @return the value of app_user.created_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.created_time
     *
     * @param createdTime the value for app_user.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.updated_time
     *
     * @return the value of app_user.updated_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.updated_time
     *
     * @param updatedTime the value for app_user.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }
}